import type { Metadata } from "next";
import { Geist, Geist_Mono,Great_Vibes } from "next/font/google";
import "./globals.css";
import ClientWrapper from "@/app/components/ClientWrapper"; // <-- Import the new component
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "CraftSpace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="/favicon-32x32.png" sizes="32x32" type="image/x-icon" />
        <link rel="apple-touch-icon" href="/android-chrome-192x192.png" /> */}
       
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased min-h-screen text-amber-400 bg-gradient-to-r from-neutral-900 to-neutral-950`}
      >
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}